utils::globalVariables(c("sample_name", "p_adj", "sig_p", "sig_p_adj", 
                         "clin_factor", "feature", "group", "pair", ".", 
                         "post_hoc_pvalue", "log2FC", "sig", "Combine_name", 
                         "p_value", "Category", "Mean", "SD", "Significant", 
                         "Group", "max_error_bar", "pvalue_text", "value", 
                         "ctrl", "mean_exp", "mean_ctrl", "FC", 
                         "m_log10_p_value", "m_log10_p_adj", "M", 
                         "lipid.category", "lipid.category.value", "sd_ctrl", 
                         "sd_exp", "Split_category", "characteristic", 
                         "sig.count", "total.count", "condition", "m.log.p", 
                         "significant", "mlogP", "significance", "p.value", 
                         "sd", "type", "group0", "group1", "pvalue_FC", "auc", 
                         "truth", "Class1", "cv_fold", "threshold", 
                         "sensitivity", "specificity", "precision", "recall", 
                         "contrib", "feature_num", "data2", "variable", "ID", 
                         "stdfvalue", "mean_value", "shapley_value", 
                         "abs_value", "log2FC.mean", "log2FC.sd", 
                         "log2FC.direction", "log2FC.meansd", "key", "exp_data",
                         "from", "cor_coef", "id", "color", "to", "width", 
                         "index", "weight", "ungroup", "is.expr", 
                         "ranking_method", "ML_method", "sele_freq", 
                         "importance", "C", "Value", "rfvalue", "ID", 
                         "stdfvalue", "mean_value", "shapley_value", 
                         "raw_value", "mean_shapley_value", "key_name", "DB", 
                         "ID", "pred_prob", "true_label", "Reference", "Freq",
                         "pct", "Prediction", "label", "sorted_id","A", "Feature importance", "a", "b", "expr.count", "feature_num_label", "highest", 
                         "lipid_amount", "lower", "name", "r", "sd_value", "sig_log2fc.pvalue_colors", 
                         "stat_compare_means", "upper", "x", "x0", "y", "y0"))
