utils::globalVariables(c(
    '.', ".env", "A", "Adduct", "Bilayer.Thickness", "Bond.type", "C", "CDB", "Category1", "Category2",
    "Category3", "Cellular.Component", "Chain", "Characteristic", 'characteristic', "condition", 'color', "contrib", "ctrl",
    "DEFINITION", "DB", "DataFrame", "Down", "EC.numbers", "Enzyme", "FA", "FA.C", "FA.DB", "FA.OH", "FA1",
    "FA1.Bond.Type", "FA1.C", "FA1.DB", "FA1.OH", "FA2", "FA2.Bond.Type", "FA2.C", "FA2.DB",
    "FA2.OH", "FA3", "FA3.Bond.Type", "FA4", "FA4.Bond.Type", "FC", "FC_cutoff", "Fun", "Function", "from",
    "GATOM.abbr", "Gene", "Grammar", "Headgroup.Charge", "InCharDeLipid", "InCharLipid",
    "id", "Index", "index", "Intrinsic.Curvature", "LCB.Bond.Type", "LCB2", "LCB_SN", "LION.Class",
    "LION.FA1", "LION.FA2", "LION.FA3", "LION.FA4", "LION.abbr", "LION_ID",
    "LIPIDMAPS.reaction.abbr", "Lateral.Diffusion", "Level", "Lipid",
    "Lipid.Maps.Category", "Lipid.Maps.Main.Class", "Lipids", "Log2FC", "Main.Class",
    "Mass", "Molecular.Species.Name", "N", "NES", "Normalized.Name", "O1", "O1.t", "O2", "O2.t", "OH",
    "OH.t", "Original.Name", "Path", "Reaction", "Reactions", "Row.names", "sample_name", "SN", "Significance",
    "Sn.Position.Name", "Species.Name", "Structural.Species.Name", "Sub.Class",
    "Sum.Formula", "Total.C", "Total.Chain.Sum", "Total.DB", "Total.FA", "Total.OH",
    "Transition.Temperature", "Up", "abund", "abund.x", "abund.y", "abundance.count",
    "all.sig", "all_of", "arrows", "as.dist", "aspect", "baseMean", "border", "chain", "chain2",
    "char", "char1", "char2", "charFeature", "char_feature", "colorRampPalette", "column",
    "combn", "contrast", "cor", "core", "count", "dashes", "data", "database", "databaseid", "density",
    "desc", "direction", "dist", "enzyme", "ester", "ether", "even", "everything", "feature","feature.x",
    "feature.y", "filter", "font.size", "from.sig", "from_label", "from_to", "fval_2factors",
    "fval_feature", "fval_group", "gene", "gene_FC_cutoff", "gene_p_cutoff",
    "gene_significant", "gene_symbol", "genes", "goslin", "group", "group1", "group2", "hclust", "head", "hover",
    "index1", "index2", "interactive_boxPlot_after", "interactive_boxPlot_before",
    "interactive_densityPlot_after", "interactive_densityPlot_before",
    "is.abundance", 'label', "label_name", "leadingEdge", "left_join", "lipid", "lipid.x", "lipid.y",
    "lipidChar", "lipid.category", "lipid.category.value", "list.FC",
    "log2FC", "log2FoldChange", 'log2FC.direction', "log2FC.mean", 'log2FC.sd', "lyso",
    "M", "main_class", "max_error_bar", "method", "mean_ctrl", "mean_exp", "m_log10_p_value",
    "n", "name", "nLipid", "negLog10p", "negLog10padj", "negLog10pval", "negLogP", "new.chain",
    "new.molecular.name", "no", "nodes", "nodes.x", "nodes.y", "notInCharDeLipid",
    "notInCharLipid", "odd", "original_group_name", "p", "p.adj.signif", "p.adjust",
    "p.signif", "p.value", "padj", "padj_2factors", "padj_feature", "padj_group", "pair", "path_length",
    "pathway", "pvalue_text", "pathway_score", "pl", "post_hoc_method", "post_hoc_padj", "post_hoc_pval",
    "pval", "pval_2factors", "pval_feature", "pval_group", "pvalue", "r", "ratio", "reaction", "ref",
    "reorder", "risk", "sd", "shadow", "shape", "sig", "sig_FC", "significance", "significant", "sig_fc.pval_color", "sig_padj", "sig_pval",
    "size", "slotNames", "smooth", "star", "static_boxPlot_after", "static_boxPlot_before",
    "static_densityPlot_after", "static_densityPlot_before", "statistic",
    "str_remove", "str_split", "str_to_lower", "sub_characteristic", "sub_class",
    "sub_feature", "sum_composition", "term", "title", "tmp", "to", "to.sig", "to_label", 'type',
    "value", "values", "width", "weight", "x", "x.x", "x0",
    "x.y", "y", "y0", "yOrder", "yText", "yes", "z"))
