utils::globalVariables(c(
    '.', ".env", "A", "Adduct", "Bilayer.Thickness", "Bond.type", "C", "CDB", "Category1", "Category2",
    "Category3", "Cellular.Component", "Chain", "Characteristic", "Class1",
    "DEFINITION", "DB", "DataFrame", "Down", "EC.numbers", "Enzyme", "FA", "FA.C", "FA.DB", "FA.OH", "FA1",
    "FA1.Bond.Type", "FA1.C", "FA1.DB", "FA1.OH", "FA2", "FA2.Bond.Type", "FA2.C", "FA2.DB",
    "FA2.OH", "FA3", "FA3.Bond.Type", "FA4", "FA4.Bond.Type", "FC", "FC_cutoff", "Feature",
    'Feature importance', "Freq", "Fun", "Function",
    "GATOM.abbr", "Gene", "Grammar", "Headgroup.Charge", "ID", "InCharDeLipid", "InCharLipid",
    "Index", "Intrinsic.Curvature", "LCB.Bond.Type", "LCB2", "LCB_SN", "LION.Class",
    "LION.FA1", "LION.FA2", "LION.FA3", "LION.FA4", "LION.abbr", "LION_ID",
    "LIPIDMAPS.reaction.abbr", "Lateral.Diffusion", "Level", "Lipid",
    "Lipid.Maps.Category", "Lipid.Maps.Main.Class", "Lipids", "Log2FC", "Main.Class",
    "Mass", "Molecular.Species.Name", "N", "NES", "Normalized.Name", "O1", "O1.t", "O2", "O2.t", "OH",
    "OH.t", "Original.Name", "Path", "Prediction", "Reaction", "Reactions", "Reference", "Row.names", "SN", "Significance",
    "Sn.Position.Name", "Species.Name", "Structural.Species.Name", "Sub.Class",
    "Sum.Formula", "Total.C", "Total.Chain.Sum", "Total.DB", "Total.FA", "Total.OH",
    "Transition.Temperature", "Up",
    "a",  "abund", "abund.x", "abund.y", "abundance.count", 'abs_value', 'across', 'alpha', "all.sig", "all_of", "arrows",
    "as.dist", "aspect", "auc", "b", "baseMean", "border", "case_when", "chain", "chain2",
    "char", "char1", "char2", "charFeature", "char_feature", 'characteristic', "colorRampPalette", "column",
    "combn", "contrast", "condition", "contrib", 'color', "cor", "cor_coef", "cor.test", "core",
    "count", "clin_factor", "ctrl", 'cv_fold',
    "dashes", "data", "database", "databaseid", "density",
    "desc", "direction", "dist", "enzyme", "ester", "ether", "even", "everything",
    "feature", "feature_num", "feature_num_label", "feature.x", "feature.y", "filter",
    "font.size", "from", "from.sig", "from_label", "from_to", "fval_2factors",
    "fval_feature", "fval_group", "gene", "gene_FC_cutoff", "gene_p_cutoff",
    "gene_significant", "gene_symbol", "genes", "goslin", "group", "group0",
    "group1", "group2", "hclust", "head", "highest", "hover", "id", "if_else", "index",
    "index1", "index2", "interactive_boxPlot_after", "interactive_boxPlot_before",
    "interactive_densityPlot_after", "interactive_densityPlot_before", "importance",
    "is.abundance", 'label', "label_name", "leadingEdge", "left_join", "lipid", "lipid.x", "lipid.y",
    "lipidChar", "lipid.category", "lipid.category.value", "list.FC", "lm",
    "log2FC", "log2FoldChange", 'log2FC.direction', "log2FC.mean", 'log2FC.sd', "lower", "lyso",
    "M", "main_class", "max_error_bar", "method", "mean_ctrl", "mean_exp", "m_log10_p_value",
    "mean_shapley_value",  "mean_value",
    "n", "name", "nLipid", "negLog10p", "negLog10padj", "negLog10pval", "negLogP", "new.chain",
    "new.molecular.name", "no", "nodes", "nodes.x", "nodes.y", "notInCharDeLipid",
    "notInCharLipid", "odd", "original_group_name", "p", "p.adj.signif", "p.adjust",
    "padj", "padj_2factors", "padj_feature", "padj_group", "pair", "path_length",
    "pathway", "pct", "pred_label", "pred_prob", "p.value", "p_value", "pvalue_FC", "pvalue_text", "pathway_score", "pl", "post_hoc_method",
    "post_hoc_padj", "post_hoc_pval", 'precision', "p.signif",
    "pval", "pval_2factors", "pval_feature", "pval_group", "pvalue", "r", "ratio",
    "raw_value", "reaction", "ref", "recall",
    "reorder", "rfvalue", "risk", "sample_name", "sensitivity", "sd", 'sd_value', "sele_freq",
    "shadow", "shape", "shap", "shap_se", "shapley_value", "sig", "sig_FC",
    "significance", "significant", "sig_fc.pval_color", "sig_padj", "sig_pval",
    "size", "slotNames", "smooth", "sorted_id", "specificity", "star", "static_boxPlot_after", "static_boxPlot_before",
    "static_densityPlot_after", "static_densityPlot_before", "statistic", "stdfvalue",
    "str_remove", "str_split", "str_to_lower", "sub_characteristic", "sub_class",
    "sub_feature", "sum_composition", "sym", "term", "threshold", "title", "tibble", "tmp", "to", "to.sig",
    "to_label", "true_label", "truth", 'type', "upper",
    "variable", "value", "values", "width", "weight", "x", "x.x", "x0",
    "x.y", "y", "y0", "yOrder", "yText", "yes", "z", "adjusted_col",".data"))
